default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: easyfeeds
  username: postgres
  password: 123456  # or your actual password
  host: localhost
  port: 5433

# test:
#   <<: *default
#   database: easyfeeds_test
#   username: postgres
#   password: password  # or your actual password
#   host: localhost
#   port: 5433

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>